xcodeproj 'Demo'
platform :ios, '8.0'
use_frameworks!

pod 'JetPack', :path => '..'


post_install do |installer|
	project = installer.pods_project

	project.targets.each do |target|
		target.build_configuration_list.build_settings('Debug')['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
		target.build_configuration_list.build_settings('Debug')['ENABLE_TESTABILITY'] = 'YES'
		target.build_configuration_list.build_settings('Release')['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
	end
end
